sudo: required
dist: trusty

services:
    - docker

language: go

go:
  - tip

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master

before_install:  
    - sudo apt-get update
    - sudo apt-get install -y docker-engine
    - sudo apt-get install -y qemu

install:
  - make bootstrap

script:
  - make travis
